services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    image: nginx:42
    depends_on:
     - wordpress
     - mariadb
    ports:
     - "443:443"
    volumes:
     - wordpress:/var/www/html
    env_file:
     - .env
    networks:
     - inception
    restart: always
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    image: wordpress:42
    depends_on:
     - mariadb
    volumes:
     - wordpress:/var/www/html
    env_file:
     - .env
    networks:
     - inception
    restart: always
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    image: mariadb:42
    volumes:
     - mariadb:/var/lib/mysql
    env_file:
     - .env
    networks:
     - inception
    restart: always
networks:
  inception:
    name: inception
volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/yokamura/data/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/yokamura/data/mariadb
                        o: bind
                        type: none
